apiVersion: v1
kind: Service

metadata:
  name: banking-app-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: banking-app

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}